version: "3.5"
services:
  db:
    image: mysql/mysql-server:8.0.30
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_HOST: "%"
    network_mode: bridge
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO
    ports:
      - "3306:3306"
    expose:
      - "3306"
